export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE"


export const CREATE_PRODUCTS = 'CREATE_PRODUCTS';
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS';
export const CREATE_PRODUCTS_FAILED = 'CREATE_PRODUCTS_FAILED';

export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAILED = 'UPDATE_PRODUCTS_FAILED';

export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAILED = 'DELETE_PRODUCTS_FAILED';